version: '3.7'

services:
  db:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fastladder
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    - ./mysql:/var/lib/mysql
    ports:
    - 3306:3306
  fastladder:
    image: hoshinotsuyoshi/fastladder
    command: foreman start -p 3000
    environment:
      TZ: Asia/Tokyo
      DATABASE_URL: mysql2://docker:docker@db/fastladder
      RAILS_ENV: production
      RAILS_SERVE_STATIC_FILES: 1
      SECRET_KEY_BASE: "PLEASE_CHANGE_THIS"
    ports:
    - 3333:3000
    depends_on:
    - db
